
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'.

Traceback (most recent call last)
File "/opt/render/project/src/.venv/lib/python3.9/site-packages/flask/app.py", line 1536, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/render/project/src/.venv/lib/python3.9/site-packages/flask/app.py", line 1514, in wsgi_app
response = self.handle_exception(e)
File "/opt/render/project/src/.venv/lib/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
response = self.full_dispatch_request()
File "/opt/render/project/src/.venv/lib/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/render/project/src/.venv/lib/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/render/project/src/.venv/lib/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
File "/opt/render/project/src/app/routes.py", line 324, in security_tools
return render_template('security_tools.html',
File "/opt/render/project/src/.venv/lib/python3.9/site-packages/flask/templating.py", line 149, in render_template
template = app.jinja_env.get_or_select_template(template_name_or_list)
File "/opt/render/project/src/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
return self.get_template(template_name_or_list, parent, globals)
File "/opt/render/project/src/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 1016, in get_template
return self._load_template(name, globals)
File "/opt/render/project/src/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 975, in _load_template
template = self.loader.load(self, name, self.make_globals(globals))
File "/opt/render/project/src/.venv/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
code = environment.compile(source, name, filename)
File "/opt/render/project/src/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 771, in compile
self.handle_exception(source=source_hint)
File "/opt/render/project/src/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
raise rewrite_traceback_stack(source=source)
File "/opt/render/project/src/app/templates/security_tools.html", line 8, in template
{% endfor %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'.
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it.

Brought to you by DON'T PANIC, y